In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 1.34857607, -0.28397869, -1.74258227, -0.11761652,  0.39996977,
       -1.6015665 , -1.65249308, -0.10353778,  1.68985081, -1.11012186])

In [6]:
B = np.random.randn(10)
B

array([ 0.52015265,  1.41521567,  0.47134729, -0.37158767, -1.01438997,
        1.59979586, -0.22334118,  0.44743847,  0.77451533,  0.69559795])

In [7]:
# Binary Functions
np.add(A,B)

array([  1.86872873e+00,   1.13123699e+00,  -1.27123498e+00,
        -4.89204187e-01,  -6.14420199e-01,  -1.77064099e-03,
        -1.87583426e+00,   3.43900691e-01,   2.46436614e+00,
        -4.14523918e-01])

In [8]:
np.maximum(A,B)

array([ 1.34857607,  1.41521567,  0.47134729, -0.11761652,  0.39996977,
        1.59979586, -0.22334118,  0.44743847,  1.68985081,  0.69559795])

In [10]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True